CREATE TABLE "Sessions" (
    id SERIAL PRIMARY KEY,
    "userId" INTEGER NOT NULL,
    "deviceId" VARCHAR(255) NOT NULL UNIQUE,
    "deviceName" VARCHAR(255) NOT NULL,
    ip VARCHAR(255) NOT NULL,
    iat TIMESTAMP NOT NULL,
    exp TIMESTAMP NOT NULL,
    FOREIGN KEY ("userId") REFERENCES "Users"(id) ON DELETE CASCADE
)