CREATE TABLE "Posts" (
    "id" SERIAL PRIMARY KEY,
    "title" VARCHAR(30) COLLATE "C" NOT NULL,
    "shortDescription" VARCHAR(100) COLLATE "C" NOT NULL,
    "content" VARCHAR(1000) COLLATE "C" NOT NULL,
    "blogId" INTEGER NOT NULL,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "deletedAt" TIMESTAMPTZ,

    CONSTRAINT fk_blog FOREIGN KEY ("blogId") REFERENCES "Blogs" ("id") ON DELETE CASCADE
);